import { redirect } from "next/navigation";
import { getSession } from "@/lib/auth";
import { TrainerCard } from "@/components/trainer-card";

// Funções utilitárias para gerar dados proporcionais
function getRandomLevel() {
  return Math.floor(Math.random() * 51); // 0 a 50
}
function getXP(level: number) {
  return level * 1000;
}
function getCollectionCount(level: number) {
  // Proporcional ao nível, com variação de até 10 para mais/menos
  const base = Math.floor((level / 50) * 386);
  const variation = Math.floor(Math.random() * 21) - 10; // -10 a +10
  return Math.max(0, Math.min(386, base + variation));
}

// Lista de pokémons para mais usados
const mostUsedPokemonList = [
  "pikachu",
  "charizard",
  "blastoise",
  "venusaur",
  "gengar",
  "alakazam",
  "snorlax",
  "lucario",
  "dragonite",
  "gardevoir",
  "tyranitar",
  "salamence",
  "metagross",
  "blaziken",
  "swampert",
];

function getRandomFrom(arr: string[]) {
  return arr[Math.floor(Math.random() * arr.length)];
}
function getRandomInt(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}
function getRandomTime() {
  // Tempo total de jogo entre 10h e 500h
  const hours = getRandomInt(10, 500);
  return `${hours}h`;
}

// Lista fixa de 50 treinadores com stats imutáveis
const fixedTrainers = [
  {
    nickname: "TrainerAsh1001",
    level: 42,
    xp: 42000,
    collectionCount: 300,
    victories: 120,
    defeats: 30,
    winRate: "80.0%",
    badges: 8,
    trophies: 3,
    mostUsed: "pikachu",
    playTime: "320h",
  },
  {
    nickname: "PokemonCatcher2345",
    level: 18,
    xp: 18000,
    collectionCount: 200,
    victories: 40,
    defeats: 20,
    winRate: "66.7%",
    badges: 3,
    trophies: 0,
    mostUsed: "weedle",
    playTime: "80h",
  },
  {
    nickname: "GymLeaderMisty3456",
    level: 36,
    xp: 36000,
    collectionCount: 250,
    victories: 90,
    defeats: 25,
    winRate: "78.3%",
    badges: 7,
    trophies: 2,
    mostUsed: "starmie",
    playTime: "210h",
  },
  {
    nickname: "AceTrainerBrock4567",
    level: 28,
    xp: 28000,
    collectionCount: 180,
    victories: 60,
    defeats: 18,
    winRate: "76.9%",
    badges: 5,
    trophies: 1,
    mostUsed: "onix",
    playTime: "150h",
  },
  {
    nickname: "PokefanDawn5678",
    level: 22,
    xp: 22000,
    collectionCount: 161,
    victories: 35,
    defeats: 15,
    winRate: "70.0%",
    badges: 4,
    trophies: 0,
    mostUsed: "piplup",
    playTime: "90h",
  },
  {
    nickname: "CollectorGary6789",
    level: 40,
    xp: 40000,
    collectionCount: 285,
    victories: 110,
    defeats: 28,
    winRate: "79.7%",
    badges: 8,
    trophies: 2,
    mostUsed: "blastoise",
    playTime: "300h",
  },
  {
    nickname: "RivalPaul7890",
    level: 34,
    xp: 34000,
    collectionCount: 156,
    victories: 85,
    defeats: 30,
    winRate: "73.9%",
    badges: 6,
    trophies: 1,
    mostUsed: "electivire",
    playTime: "180h",
  },
  {
    nickname: "RocketJessie8901",
    level: 25,
    xp: 25000,
    collectionCount: 145,
    victories: 50,
    defeats: 25,
    winRate: "66.7%",
    badges: 3,
    trophies: 0,
    mostUsed: "arbok",
    playTime: "120h",
  },
  {
    nickname: "MysticJames9012",
    level: 27,
    xp: 27000,
    collectionCount: 132,
    victories: 55,
    defeats: 22,
    winRate: "71.4%",
    badges: 4,
    trophies: 0,
    mostUsed: "weezing",
    playTime: "130h",
  },
  {
    nickname: "ValorMay1023",
    level: 30,
    xp: 30000,
    collectionCount: 130,
    victories: 70,
    defeats: 20,
    winRate: "77.8%",
    badges: 6,
    trophies: 1,
    mostUsed: "blaziken",
    playTime: "160h",
  },
  {
    nickname: "InstinctTracey1123",
    level: 19,
    xp: 19000,
    collectionCount: 89,
    victories: 32,
    defeats: 18,
    winRate: "64.0%",
    badges: 3,
    trophies: 0,
    mostUsed: "scyther",
    playTime: "70h",
  },
  {
    nickname: "TrainerSerena1224",
    level: 24,
    xp: 24000,
    collectionCount: 102,
    victories: 48,
    defeats: 19,
    winRate: "71.6%",
    badges: 4,
    trophies: 0,
    mostUsed: "sylveon",
    playTime: "110h",
  },
  {
    nickname: "PokemonCatcherMax1325",
    level: 16,
    xp: 16000,
    collectionCount: 97,
    victories: 22,
    defeats: 12,
    winRate: "64.7%",
    badges: 2,
    trophies: 0,
    mostUsed: "zigzagoon",
    playTime: "50h",
  },
  {
    nickname: "GymLeaderIris1426",
    level: 38,
    xp: 38000,
    collectionCount: 234,
    victories: 100,
    defeats: 27,
    winRate: "78.7%",
    badges: 7,
    trophies: 2,
    mostUsed: "haxorus",
    playTime: "220h",
  },
  {
    nickname: "AceTrainerCilan1527",
    level: 21,
    xp: 21000,
    collectionCount: 211,
    victories: 30,
    defeats: 14,
    winRate: "68.2%",
    badges: 3,
    trophies: 0,
    mostUsed: "simisage",
    playTime: "75h",
  },
  {
    nickname: "PokefanBonnie1628",
    level: 14,
    xp: 14000,
    collectionCount: 198,
    victories: 18,
    defeats: 8,
    winRate: "69.2%",
    badges: 2,
    trophies: 0,
    mostUsed: "dedenne",
    playTime: "40h",
  },
  {
    nickname: "CollectorClemont1729",
    level: 29,
    xp: 29000,
    collectionCount: 178,
    victories: 62,
    defeats: 21,
    winRate: "74.7%",
    badges: 5,
    trophies: 1,
    mostUsed: "heliolisk",
    playTime: "140h",
  },
  {
    nickname: "RivalGladion1830",
    level: 33,
    xp: 33000,
    collectionCount: 239,
    victories: 80,
    defeats: 26,
    winRate: "75.5%",
    badges: 6,
    trophies: 1,
    mostUsed: "silvally",
    playTime: "170h",
  },
  {
    nickname: "RocketJames1931",
    level: 23,
    xp: 23000,
    collectionCount: 187,
    victories: 36,
    defeats: 17,
    winRate: "67.9%",
    badges: 3,
    trophies: 0,
    mostUsed: "carnivine",
    playTime: "85h",
  },
  {
    nickname: "MysticLillie2032",
    level: 20,
    xp: 20000,
    collectionCount: 289,
    victories: 28,
    defeats: 13,
    winRate: "68.3%",
    badges: 3,
    trophies: 0,
    mostUsed: "clefairy",
    playTime: "60h",
  },
  {
    nickname: "ValorKiawe2133",
    level: 35,
    xp: 35000,
    collectionCount: 210,
    victories: 75,
    defeats: 22,
    winRate: "77.3%",
    badges: 7,
    trophies: 2,
    mostUsed: "typhlosion",
    playTime: "175h",
  },
  {
    nickname: "InstinctMallow2234",
    level: 21,
    xp: 21000,
    collectionCount: 120,
    victories: 28,
    defeats: 14,
    winRate: "66.7%",
    badges: 3,
    trophies: 0,
    mostUsed: "bellossom",
    playTime: "65h",
  },
  {
    nickname: "TrainerSophocles2335",
    level: 27,
    xp: 27000,
    collectionCount: 140,
    victories: 40,
    defeats: 18,
    winRate: "68.9%",
    badges: 4,
    trophies: 0,
    mostUsed: "ampharos",
    playTime: "90h",
  },
  {
    nickname: "PokemonCatcherLana2436",
    level: 23,
    xp: 23000,
    collectionCount: 110,
    victories: 32,
    defeats: 13,
    winRate: "71.1%",
    badges: 3,
    trophies: 0,
    mostUsed: "azumarill",
    playTime: "70h",
  },
  {
    nickname: "GymLeaderIlima2537",
    level: 29,
    xp: 29000,
    collectionCount: 160,
    victories: 55,
    defeats: 20,
    winRate: "73.3%",
    badges: 5,
    trophies: 1,
    mostUsed: "gumshoos",
    playTime: "120h",
  },
  {
    nickname: "AceTrainerHau2638",
    level: 26,
    xp: 26000,
    collectionCount: 135,
    victories: 38,
    defeats: 16,
    winRate: "70.4%",
    badges: 4,
    trophies: 0,
    mostUsed: "decidueye",
    playTime: "85h",
  },
  {
    nickname: "PokefanMina2739",
    level: 22,
    xp: 22000,
    collectionCount: 100,
    victories: 30,
    defeats: 12,
    winRate: "71.4%",
    badges: 3,
    trophies: 0,
    mostUsed: "ribombee",
    playTime: "60h",
  },
  {
    nickname: "CollectorWicke2840",
    level: 24,
    xp: 24000,
    collectionCount: 115,
    victories: 34,
    defeats: 15,
    winRate: "69.4%",
    badges: 4,
    trophies: 0,
    mostUsed: "goodra",
    playTime: "75h",
  },
  {
    nickname: "RivalGuzma2941",
    level: 32,
    xp: 32000,
    collectionCount: 170,
    victories: 60,
    defeats: 25,
    winRate: "70.6%",
    badges: 6,
    trophies: 1,
    mostUsed: "golisopod",
    playTime: "130h",
  },
  {
    nickname: "RocketPlumeria3042",
    level: 28,
    xp: 28000,
    collectionCount: 150,
    victories: 45,
    defeats: 19,
    winRate: "70.3%",
    badges: 5,
    trophies: 1,
    mostUsed: "salazzle",
    playTime: "100h",
  },
  {
    nickname: "MysticFaba3143",
    level: 25,
    xp: 25000,
    collectionCount: 120,
    victories: 36,
    defeats: 15,
    winRate: "70.6%",
    badges: 4,
    trophies: 0,
    mostUsed: "hypno",
    playTime: "80h",
  },
  {
    nickname: "ValorMolayne3244",
    level: 27,
    xp: 27000,
    collectionCount: 140,
    victories: 42,
    defeats: 17,
    winRate: "71.2%",
    badges: 4,
    trophies: 0,
    mostUsed: "magnezone",
    playTime: "90h",
  },
  {
    nickname: "InstinctAcerola3345",
    level: 23,
    xp: 23000,
    collectionCount: 110,
    victories: 29,
    defeats: 13,
    winRate: "69.0%",
    badges: 3,
    trophies: 0,
    mostUsed: "mimikyu",
    playTime: "65h",
  },
  {
    nickname: "TrainerNanu3446",
    level: 21,
    xp: 21000,
    collectionCount: 100,
    victories: 25,
    defeats: 11,
    winRate: "69.4%",
    badges: 3,
    trophies: 0,
    mostUsed: "alolan-persian",
    playTime: "55h",
  },
  {
    nickname: "PokemonCatcherHapu3547",
    level: 24,
    xp: 24000,
    collectionCount: 120,
    victories: 33,
    defeats: 14,
    winRate: "70.2%",
    badges: 4,
    trophies: 0,
    mostUsed: "mudsdale",
    playTime: "70h",
  },
  {
    nickname: "GymLeaderMohn3648",
    level: 26,
    xp: 26000,
    collectionCount: 130,
    victories: 37,
    defeats: 16,
    winRate: "69.8%",
    badges: 4,
    trophies: 0,
    mostUsed: "oranguru",
    playTime: "80h",
  },
  {
    nickname: "AceTrainerLusamine3749",
    level: 29,
    xp: 29000,
    collectionCount: 150,
    victories: 44,
    defeats: 18,
    winRate: "71.0%",
    badges: 5,
    trophies: 1,
    mostUsed: "nihilego",
    playTime: "95h",
  },
  {
    nickname: "PokefanGladion3850",
    level: 27,
    xp: 27000,
    collectionCount: 140,
    victories: 39,
    defeats: 16,
    winRate: "70.9%",
    badges: 4,
    trophies: 0,
    mostUsed: "silvally",
    playTime: "85h",
  },
  {
    nickname: "CollectorLillie3951",
    level: 22,
    xp: 22000,
    collectionCount: 110,
    victories: 28,
    defeats: 12,
    winRate: "70.0%",
    badges: 3,
    trophies: 0,
    mostUsed: "clefairy",
    playTime: "60h",
  },
  {
    nickname: "RivalKukui4052",
    level: 30,
    xp: 30000,
    collectionCount: 160,
    victories: 50,
    defeats: 20,
    winRate: "71.4%",
    badges: 6,
    trophies: 1,
    mostUsed: "incineroar",
    playTime: "110h",
  },
  {
    nickname: "RocketBurnet4153",
    level: 25,
    xp: 25000,
    collectionCount: 120,
    victories: 35,
    defeats: 15,
    winRate: "70.0%",
    badges: 4,
    trophies: 0,
    mostUsed: "delphox",
    playTime: "75h",
  },
  {
    nickname: "MysticOak4254",
    level: 40,
    xp: 40000,
    collectionCount: 200,
    victories: 100,
    defeats: 30,
    winRate: "76.9%",
    badges: 8,
    trophies: 2,
    mostUsed: "venusaur",
    playTime: "200h",
  },
  {
    nickname: "ValorElm4355",
    level: 32,
    xp: 32000,
    collectionCount: 150,
    victories: 48,
    defeats: 19,
    winRate: "71.6%",
    badges: 6,
    trophies: 1,
    mostUsed: "meganium",
    playTime: "100h",
  },
  {
    nickname: "InstinctBirch4456",
    level: 28,
    xp: 28000,
    collectionCount: 140,
    victories: 42,
    defeats: 17,
    winRate: "71.2%",
    badges: 5,
    trophies: 1,
    mostUsed: "sceptile",
    playTime: "90h",
  },
  {
    nickname: "TrainerRowan4557",
    level: 26,
    xp: 26000,
    collectionCount: 130,
    victories: 37,
    defeats: 16,
    winRate: "69.8%",
    badges: 4,
    trophies: 0,
    mostUsed: "torterra",
    playTime: "80h",
  },
  {
    nickname: "PokemonCatcherJuniper4658",
    level: 24,
    xp: 24000,
    collectionCount: 120,
    victories: 33,
    defeats: 14,
    winRate: "70.2%",
    badges: 4,
    trophies: 0,
    mostUsed: "serperior",
    playTime: "70h",
  },
  {
    nickname: "GymLeaderSycamore4759",
    level: 29,
    xp: 29000,
    collectionCount: 150,
    victories: 44,
    defeats: 18,
    winRate: "71.0%",
    badges: 5,
    trophies: 1,
    mostUsed: "chesnaught",
    playTime: "95h",
  },
  {
    nickname: "AceTrainerMagnolia4860",
    level: 27,
    xp: 27000,
    collectionCount: 140,
    victories: 39,
    defeats: 16,
    winRate: "70.9%",
    badges: 4,
    trophies: 0,
    mostUsed: "rillaboom",
    playTime: "85h",
  },
  {
    nickname: "PokefanSonia4961",
    level: 22,
    xp: 22000,
    collectionCount: 110,
    victories: 28,
    defeats: 12,
    winRate: "70.0%",
    badges: 3,
    trophies: 0,
    mostUsed: "yamper",
    playTime: "60h",
  },
  {
    nickname: "CollectorHop5062",
    level: 30,
    xp: 30000,
    collectionCount: 160,
    victories: 50,
    defeats: 20,
    winRate: "71.4%",
    badges: 6,
    trophies: 1,
    mostUsed: "dubwool",
    playTime: "110h",
  },
];

export { fixedTrainers };
export default async function TrainersPage() {
  const session = await getSession();

  if (!session) {
    redirect("/");
  }

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold text-blue-800">Treinadores</h1>
      <div className="flex flex-wrap gap-6">
        {fixedTrainers.map((trainer, idx) => (
          <TrainerCard key={idx} {...trainer} />
        ))}
      </div>
    </div>
  );
}
